### PR TITLE
Add native asset info.

### PR DESCRIPTION
**Pull request by azhurauski-sc**
~Can be reviewed, however native asset id is incorrect, need to find prober one and check is it available through API.~
~I found the following assetId: `51f33a2f14f92735e562dc658a5639279ddca3d5079a6d1242b2a588a9cbf44c` but api doesn't return any data for it.~

### CODE REVIEW

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Could we try putting the "verified" chip in the asset name container?

The reason I ask is because the column alignment for $IRON isn't consistent with the column below in the "All Assets" list. 

Making these look consistent is probably going to be tricky but would be ideal.

**Review by ndemidovich-sc — APPROVED** [review]

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Anywhere in the explorer where we show a hash, it's using 4 sections of truncation, "0000...2341...143d1...d13d". 

Can we reduce this to 3 sections of truncation, "0000...qfqf...d13d".

This way all our lists can have more breathing space. In particular in this page where we've redistributed the columns, it should make the spacing feel more balanced.

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Ideally each resolution would have the same column layout. 
Screen Shot 2023-05-03 at 10 44 38 AM

Screen Shot 2023-05-03 at 10 44 32 AM

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Supply column would look better if it was aligned with the created column

Screen Shot 2023-05-03 at 11 05 30 AM

**Review by skylarrichard123 — APPROVED** [review]

**Pull request merged**
