### PR TITLE
Add Time Since Last Block

### PR DESCRIPTION
**Pull request by deekerno**
## Summary
Adds Time Since Last Block field to both the block list and the block detail page.

## Testing Plan
Manually synced blocks to the API and verified proper behavior on explorer.

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dguenther** [comment]
Do you mind updating some of these values on staging to make it easier to preview? It looks good preliminarily, though!

**Comment by deekerno** [comment]
Data is in!

**Comment by dguenther** [comment]
The math here should probably be a bit different (I'm guessing `floor`) -- as is, if you look at these two blocks, it says they're 6 seconds apart but the timestamps appear to be 5 seconds apart https://block-explorer-git-iro-1398-ironfish.vercel.app/blocks/40297 and https://block-explorer-git-iro-1398-ironfish.vercel.app/blocks/40296

**Comment by deekerno** [comment]
> The math here should probably be a bit different (I'm guessing `floor`) -- as is, if you look at these two blocks, it says they're 6 seconds apart but the timestamps appear to be 5 seconds apart https://block-explorer-git-iro-1398-ironfish.vercel.app/blocks/40297 and https://block-explorer-git-iro-1398-ironfish.vercel.app/blocks/40296

So I had originally calculated the difference in milliseconds and then changed the units to seconds, but I decided to use the same logic that we were using for the time since last block in the metrics display. I can adjust the math to something more nuanced or we can have decimals in the since last block column.

**Comment by dguenther** [comment]
That calculation should probably change too then, otherwise it looks like an off-by-one error for anyone calculating the numbers manually. I don't think millisecond resolution is that useful right now, unless we're going to show it for the timestamp as well, but even then I'd probably suggest hiding it behind some kind of "more details" hover state or pane.

**Comment by deekerno** [comment]
Pending a change in the API, I've decided to show two decimal places to show that the block times are more precise than what is initially shown.

**Review by dguenther — APPROVED** [review]
Looks good!

**Comment by dguenther** [comment]
There are a couple styling tweaks I'd suggest here, but I'm okay merging this and following up in separate PRs.

**Pull request merged**
