### PR TITLE
Use table for transactions i\o and mints\burns lists.

### PR DESCRIPTION
**Pull request by azhurauski-sc**
Use two table instead of list for transactions inputs outputs, mints and burns.
Added empty message when no mints and burns in low resolution.
Didn't manage to reproduce case for date in browser.

### CODE REVIEW

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Screen Shot 2023-03-17 at 10 11 48 AM
"Quantity" should be left aligned with the #

**Comment by azhurauski-sc** [comment]
> Screen Shot 2023-03-17 at 10 11 48 AM
> 
> "Quantity" should be left aligned with the #

Fixed, empty state for mints and burns shows separately in two columns and have one message when they become one column.

**Comment by skylarrichard123** [comment]
Screen Shot 2023-03-21 at 1 37 33 PM

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
lets remove quantity when there aren't any

**Comment by azhurauski-sc** [comment]
> lets remove quantity when there aren't any

Done.

**Review by skylarrichard123 — APPROVED** [review]

**Review by ndemidovich-sc — APPROVED** [review]

**Pull request merged**
