### PR TITLE
Add forked status for transaction

### PR DESCRIPTION
**Pull request by hairtail**
Add forked status for transaction, all blocks that mined this transaction are on forked chain.
Issue https://github.com/iron-fish/block-explorer-v2/issues/98

### CODE REVIEW

**Comment by hairtail** [comment]
Some transactions were mined by forked blocks while we can't get this status in transaction page. https://github.com/iron-fish/ironfish/issues/2115. There are so many mining pools, so there are too many payout transactions from pool to miners. This issue certainly makes we all confused. That's why we need this PR. Looking forward to your reply.

**Comment by NullSoldier** [comment]
This is a good idea, do you have a link to a transaction thats forked to test this? We'll also need review from our designer.

**Comment by hairtail** [comment]
> This is a good idea, do you have a link to a transaction thats forked to test this? We'll also need review from our designer.

Yes, I have. This is coinbase transaction of a forked block. You can have a try with it.
`4999c55811c6e204a7001e9d76e5028077e6d451b631465c5ba96fe5b485bf5f`

**Comment by azhurauski-sc** [comment]
Badge message updated and added to transaction page in this PR https://github.com/iron-fish/block-explorer/pull/108.

**Comment by hairtail** [comment]
> Badge message updated and added to transaction page in this PR #108.

Sorry. I can't really understand why there is a new PR while that one is almost same as this one.

**Comment by azhurauski-sc** [comment]
> Sorry. I can't really understand why there is a new PR while that one is almost same as this one.
I made it because it brings required changes and resulting changes in one commit. Merged you PR, thanks.

**Comment by NullSoldier** [comment]
Sorry @hairtail for the duplication. Our front end team missed your PR and that it accomplished an ask by our designer. We'll still give you test net credit for doing this work.

**Pull request merged**
